services:
  voice_service:
    container_name: voice_service
    hostname: voice_service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "50052:50052"
    environment:
      - PORT=50052
      - MONGODB_URI=mongodb+srv://kanawatgrill2002:kW6RGhf25O5ZJuLf@newsscraping.aemzc.mongodb.net/?retryWrites=true&w=majority&appName=NewsScraping
      - KAFKA_BROKER=broker:29092
    networks:
      - app_network

networks:
  app_network:
    external: true
